### ISSUE TITLE
Issue: No service registered for QueryValidator

### ISSUE THREAD

**Issue by bpkinez** [bbartels/Delve#9]
Hi Benjamin,

when I have class User without UserQueryValidator part like:

```cs
    public class User
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }

        public IEnumerable<UserRole> UserRoles { get; set; }

        public User() { }

        public User(string firstName, string lastName, DateTime dateOfBirth)
        {
            FirstName = firstName;
            LastName = lastName;
            DateOfBirth = dateOfBirth;
        }
    }
```
and call http://localhost:{port}/api/user i get exception **RuntimeException: No service registered for QueryValidator: Delve.Models.Validation.IQueryValidator`1[Delve.Demo.Models.User]**, but I don't want to have any query validation on User class in this case.

**Comment by bbartels** [comment]
This is a limitation right now, there is no way for you to use an Entity without an Entity validator.
So I would just suggest creating a validator for the User entity and call AllowAll on each property.

Also I don't think I'll change this going forward, because adding a QueryValidator to an entity implies intent. So if you accidentally forget to add one I don't think it would be good to automatically expose all properties to be filtered selected and sorted.

I may however add an overload to AllowAll() at some point that will automatically add all native properties to be filtered, sorted and selected.

**Comment by bpkinez** [comment]
Ok, thanks.
